### ISSUE TITLE
Next button does not load the new image in the first click

### ISSUE THREAD

**Issue by getsanjeev** [sumit3203/ACTIVESEGMENTATION#22]
This is a small bug, next button does not load the second image for the first time (not desired), but when clicked second time it loads third image (desired) and then everything works properly.

**Comment by amit6663** [comment]
@sumit3203 I want to work on this issue?

**Comment by amit6663** [comment]
@sumit3203 is there communication channel pls provide me.

**Comment by Himanshu664** [comment]
I am on it.

**Comment by ankit5646** [comment]
I would like to work on that,  I'm new to open source, please provide details @sumit3203 .

**Comment by Raghavendrapara** [comment]
@ankit5646 Please set up the repository on your local machine and have the basic UI running.

**Comment by Raghavendrapara** [comment]
Use eclipse preferably, will align easily.

After the cloning for the project structure -> set up JDK 8 and add the jars present in the jars folder to External libraries section

**Comment by aaryan-gautam** [comment]
@Raghavendrapara I am still getting issues after adding the IJ jar file to jars folder. However, my eclipse still runs into errors. The import statements like https://github.com/sumit3203/ACTIVESEGMENTATION/blob/53ab23776d27832dccac8ab37f6ad393350d9583/src/Active_Segmentation_.java#L8 lead to compilation issues as my eclipse is not able to import. Do you have how to proceed with this?

**Comment by Raghavendrapara** [comment]
did you add the IJ.jar to classpath ?

**Comment by aaryan-gautam** [comment]
@Raghavendrapara That fixed the issues! 

When I create a new project, it creates a training folder but every folder inside is empty due to which I am not able to open this existing project. What steps should I take to ensure that I am able to open an existing project to recreate this bug?

I was also facing some compilation issues when I tried to run TestOnlineCells3.java with the following error as the ResultsTable is not able to find a method for getDefaultHeading. Are you aware of what could be leading to this issue?
![image](https://user-images.githubusercontent.com/64756497/230571839-ad39d431-f5d7-41b3-a434-234f9915433f.png)

**Comment by sumit3203** [comment]
Download imageJ from https://imagej.nih.gov/ij/download.html and import that IJ.jar. This issue should be resolved but you don't have the data so you will get the directory error.

**Comment by aaryan-gautam** [comment]
@sumit3203 I have imported the IJ.jar from the download link above. 
![image](https://user-images.githubusercontent.com/64756497/230577872-93983353-96a8-4a1e-ac60-a4eee8955869.png)
This is what my buildpath looks like since I just moved the ij.jar file from the download.
![image](https://user-images.githubusercontent.com/64756497/230578178-369a28fb-6bc9-4287-a561-174e1568afe0.png)

For the data I was attempting to use https://zenodo.org/record/7652728#.ZC_bT3bMJPY linked at https://neurostars.org/t/gsoc-2023-project-idea-18-2-image-feature-and-classification-database-350-h/24596/11 by Dimiter

**Comment by sumit3203** [comment]
Looks fine to me. Please create a custom test class and write String headings[]=ResultsTable.getDefaultHeadings(); and print headings length to check whether its working or not ? I am not able to reproduce the error.

**Comment by Raghavendrapara** [comment]
Hi Sumit,
Probably they have introduced a update in the API

String headings[]=ResultsTable.getResultsTable().getHeadings();

changing ResultsTable.getDefaultHeadings() to above might work;

getDefaultHeadings() -> getDefaultHeadings(int index)  demands a index

**Comment by aaryan-gautam** [comment]
@sumit3203 @Raghavendrapara I was able to get it working by making this change as suggested. `String headings[]=ResultsTable.getResultsTable().getHeadings();`  However, I get the following crash error on console https://pastebin.com/zTMekuk9 when running TestOnlineCells3.java with the path for hela/Endosome as the directory path.

I also wanted to know if I could create a project using the hela directory from https://zenodo.org/record/7652728#.ZDO1knbMJPa and what steps can I take to create a project from this screen?
![image](https://user-images.githubusercontent.com/64756497/230846655-0b979711-0926-4440-b3e6-512b39d76bf2.png)

**Comment by dprodanov** [comment]
We have never tested on pastebin. You should run Java locally on your PC.

**Comment by aaryan-gautam** [comment]
It is run locally on my PC. I just pasted the error message on pastebin because it was too long to take a screenshot of.

**Comment by Jharkhar** [comment]
I would like to work on that, has the issue was resolved or not please let me know @aaryan-gautam.
